language: node_js
node_js: stable
sudo: required
addons:
  chrome: stable
script:
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
    - secure: >-
        RuhtP6udVFkfewxXfJWtzJH4ivxC5wJ6ExcVWwnudJWiANgPVYAeIIxwyONcfW/zt3uV611E0BIxPo4xjDyAEuKRTEwRoELPw/EyZ3MK5N48RKWf3Gqtzjg3ftJ0feRBh/io74PGgz6NwoFqOGEDrJAjrYGdSHbFMhTabZzkszfz7fMg986wk9PIXfqMVmC9P+1wB27QHPXILXkuFb9ETsmOet6w0vMrq9KKvIDnC/XYe81vvmW93EDtKlxGcVa+QKp+FAI1I1ShoP8oHMAQp61O5CN8Iurik/v0ZX1aAHTppJvTsL3QPKEdF1eqAFuAkhzyNXy91+pQVRk1bcrUePakIFsQNFoun4tDDVMb6hF5u9ng3obaEzvFVkA3znxMrOeuJfTzAaJPKVVtwq53Fy4jKIl4IdTaU6ttfYWrA6xr7+BUL6NRdEGJNEEePvEkMY6WEWq75MdDtcGhPj7N5NSV4TYZTT8G7FtP4Uv3W26lMcgVi5qkNTisVOFJH35m4sx/yQ0bfk0SAo9hlq/aD+YwNK3AqX3LF8wt3FR4dkqGrX9LlscfJBCj0RpSaldLtkxwdTCqfzcJ1ZkP9qpjdmGiWBonOaPcN6w1wxMNZxWcOKHk4GYEP7yeJCCgZFVWIZkutqmNiGRA5nEgkpEuCs1iOLFUtFgBBVlUNa5/DXw=
    - secure: >-
        udizwjNb/KaMW0aW9b47XPrLWN7niazsARMRFl+Fd2vbtua6t62NzmmItZTo0znww1KU5mVfZyaMCNxRYI7KssBX56zfx8vvay5i+Crleey1KvbFdipW/VdB3fexyh59CoFGb/9Hzg/Cb8jDkmD5VcN3GkWny9tsAvz+A4aa65rGdNiU2ivcuR7bh2nlSzCrzUCdAb0E2VcfQ6+uTj7NEyy8D30lDF3kkg3UONPOGdNggtefgSla6WiuZtEm2F0yq1j30UHCCHXV4utfhPH0fTMRgkR/pAUI8cqscaOV+i6zieRh8v39XuTdvaPnAmz+jEX+TilSawJ1PRM6seSS+RPEYUesx21jSbokmeS8rstUwGAUCDg8K3VwdKXSkPQN4m93IfhHPDYwBFkdnzCos+fkbSAgpjny5o0A1AR2rNom3ti/zXa3PamtSb4DOEoJGeaQ3qrNEWPey93go0s9FfH5uqS6cU4pJNmV/5oXrl7H4wihT5zw4v2VuW+frgu0rFyK6vYb4qr2UrO1nVcRva7LxSbBKYnsi+x0wjVPV7qBzNEv4ytBtdS5X1tyQOX4Sk/LloF5dHDSbFTBBwJ/M+5/TofzjM8dpHjgLszYVIvamRVBycqbI5HdFay3mqaNEoukfLWKSdlxBS05pldl4zSKC9gW32+Yis111ZEWjtA=
